### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_resnet' in keras_retinanet/models/resnet.py

### ISSUE THREAD

**Issue by Miclita** [Nellaker-group/TowardsDeepPhenotyping#6]
Hi, I am very interested in your work. 
When I ran the script "keras_retinanet/bin/evaluate.py", the error “ModuleNotFoundError” occured. I can't find it anywhere. Could you upload this module as well?

**Comment by GlastonburyC** [comment]
There is no Module missing. Everything is there. Is it possible you supply more information on the error message and `Traceback` output? - I assume you're using the wrong version of Keras.

**Comment by Miclita** [comment]
> There is no Module missing. Everything is there. Is it possible you supply more information on the error message and `Traceback` output? - I assume you're using the wrong version of Keras.
Sorry for no details of this problem. The Traceback is as follows:
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "./keras_retinanet/bin/evaluate.py", line 37, in <module>
>     from ..models.resnet import custom_objects
>   File "./keras_retinanet/bin\..\..\keras_retinanet\models\resnet.py", line 20, in <module>
>     import keras_resnet
> ModuleNotFoundError: No module named 'keras_resnet'

**Comment by Miclita** [comment]
> There is no Module missing. Everything is there. Is it possible you supply more information on the error message and `Traceback` output? - I assume you're using the wrong version of Keras.

Sorry for no detail of this problem. The Traceback is as follows:


```
Using TensorFlow backend.
Traceback (most recent call last):
File "./keras_retinanet/bin/evaluate.py", line 37, in 
from ..models.resnet import custom_objects
File "./keras_retinanet/bin....\keras_retinanet\models\resnet.py", line 20, in 
import keras_resnet
ModuleNotFoundError: No module named 'keras_resnet'
```
